In [1]:
import pandas as pd

In [2]:
wafer = pd.read_csv(r'C:\Users\Admin\Desktop\WaferFaultDetectionnn\notebooks\data\wafer_23012020_041211 (1).csv')
wafer.head()

,Unnamed: 0,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,Wafer-801,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1
1,Wafer-802,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1
2,Wafer-803,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1
3,Wafer-804,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,...,NaN,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876,-1
4,Wafer-805,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,...,NaN,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876,-1

In [3]:
wafer.drop('Unnamed: 0',axis=1,inplace=True)

In [4]:
wafer.head(3)

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,-0.0279,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1
1,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,0.0084,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1
2,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,0.0138,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1

## Dropping Unnecessary Columns

In [5]:
cols_needs_to_drop = []

for i in wafer.columns :
    if wafer[i].std() == 0 :
        cols_needs_to_drop.append(i)

cols_needs_to_drop

['Sensor-6',
 'Sensor-14',
 'Sensor-43',
 'Sensor-50',
 'Sensor-53',
 'Sensor-70',
 'Sensor-75',
 'Sensor-98',
 'Sensor-142',
 'Sensor-150',
 'Sensor-179',
 'Sensor-180',
 'Sensor-187',
 'Sensor-190',
 'Sensor-191',
 'Sensor-192',
 'Sensor-193',
 'Sensor-194',
 'Sensor-195',
 'Sensor-207',
 'Sensor-210',
 'Sensor-227',
 'Sensor-230',
 'Sensor-231',
 'Sensor-232',
 'Sensor-233',
 'Sensor-234',
 'Sensor-235',
 'Sensor-236',
 'Sensor-237',
 'Sensor-238',
 'Sensor-241',
 'Sensor-242',
 'Sensor-243',
 'Sensor-244',
 'Sensor-257',
 'Sensor-258',
 'Sensor-259',
 'Sensor-260',
 'Sensor-261',
 'Sensor-262',
 'Sensor-263',
 'Sensor-264',
 'Sensor-265',
 'Sensor-266',
 'Sensor-267',
 'Sensor-277',
 'Sensor-285',
 'Sensor-314',
 'Sensor-315',
 'Sensor-316',
 'Sensor-323',
 'Sensor-326',
 'Sensor-327',
 'Sensor-328',
 'Sensor-329',
 'Sensor-330',
 'Sensor-331',
 'Sensor-343',
 'Sensor-348',
 'Sensor-365',
 'Sensor-370',
 'Sensor-371',
 'Sensor-372',
 'Sensor-373',
 'Sensor-374',
 'Sensor-375',
 'Sensor-376',
 'Sensor-379',
 'Sensor-380',
 'Sensor-381',
 'Sensor-382',
 'Sensor-395',
 'Sensor-396',
 'Sensor-397',
 'Sensor-398',
 'Sensor-399',
 'Sensor-400',
 'Sensor-401',
 'Sensor-402',
 'Sensor-403',
 'Sensor-404',
 'Sensor-405',
 'Sensor-415',
 'Sensor-423',
 'Sensor-450',
 'Sensor-451',
 'Sensor-452',
 'Sensor-459',
 'Sensor-462',
 'Sensor-463',
 'Sensor-464',
 'Sensor-465',
 'Sensor-466',
 'Sensor-467',
 'Sensor-479',
 'Sensor-482',
 'Sensor-499',
 'Sensor-502',
 'Sensor-503',
 'Sensor-504',
 'Sensor-505',
 'Sensor-506',
 'Sensor-507',
 'Sensor-508',
 'Sensor-509',
 'Sensor-510',
 'Sensor-513',
 'Sensor-514',
 'Sensor-515',
 'Sensor-516',
 'Sensor-529',
 'Sensor-530',
 'Sensor-531',
 'Sensor-532',
 'Sensor-533',
 'Sensor-534',
 'Sensor-535',
 'Sensor-536',
 'Sensor-537',
 'Sensor-538',
 'Sensor-539']

In [6]:
ratios = wafer.isna().sum().div(100)
ratios

Sensor-1      0.01
Sensor-2      0.00
Sensor-3      0.03
Sensor-4      0.03
Sensor-5      0.03
              ...
Sensor-587    0.00
Sensor-588    0.00
Sensor-589    0.00
Sensor-590    0.00
Good/Bad      0.00
Length: 591, dtype: float64

In [7]:
cols_with_many_nun = list(ratios[ratios > 0.75].index)
cols_with_many_nun

['Sensor-158', 'Sensor-159', 'Sensor-293', 'Sensor-294']

In [8]:
wafer.drop(cols_needs_to_drop,axis=1,inplace=True)
wafer.drop(cols_with_many_nun,axis=1,inplace=True)

In [9]:
wafer.shape

(100, 465)

In [10]:
wafer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Columns: 465 entries, Sensor-1 to Good/Bad
dtypes: float64(458), int64(7)
memory usage: 363.4 KB

In [11]:
num_cols = wafer.select_dtypes(exclude='object').columns

In [33]:
num_cols = num_cols[:-1]
num_cols = list(num_cols)
print(num_cols)

['Sensor-1', 'Sensor-2', 'Sensor-3', 'Sensor-4', 'Sensor-5', 'Sensor-7', 'Sensor-8', 'Sensor-9', 'Sensor-10', 'Sensor-11', 'Sensor-12', 'Sensor-13', 'Sensor-15', 'Sensor-16', 'Sensor-17', 'Sensor-18', 'Sensor-19', 'Sensor-20', 'Sensor-21', 'Sensor-22', 'Sensor-23', 'Sensor-24', 'Sensor-25', 'Sensor-26', 'Sensor-27', 'Sensor-28', 'Sensor-29', 'Sensor-30', 'Sensor-31', 'Sensor-32', 'Sensor-33', 'Sensor-34', 'Sensor-35', 'Sensor-36', 'Sensor-37', 'Sensor-38', 'Sensor-39', 'Sensor-40', 'Sensor-41', 'Sensor-42', 'Sensor-44', 'Sensor-45', 'Sensor-46', 'Sensor-47', 'Sensor-48', 'Sensor-49', 'Sensor-51', 'Sensor-52', 'Sensor-54', 'Sensor-55', 'Sensor-56', 'Sensor-57', 'Sensor-58', 'Sensor-59', 'Sensor-60', 'Sensor-61', 'Sensor-62', 'Sensor-63', 'Sensor-64', 'Sensor-65', 'Sensor-66', 'Sensor-67', 'Sensor-68', 'Sensor-69', 'Sensor-71', 'Sensor-72', 'Sensor-73', 'Sensor-74', 'Sensor-76', 'Sensor-77', 'Sensor-78', 'Sensor-79', 'Sensor-80', 'Sensor-81', 'Sensor-82', 'Sensor-83', 'Sensor-84', 'Sensor-85', 'Sensor-86', 'Sensor-87', 'Sensor-88', 'Sensor-89', 'Sensor-90', 'Sensor-91', 'Sensor-92', 'Sensor-93', 'Sensor-94', 'Sensor-95', 'Sensor-96', 'Sensor-97', 'Sensor-99', 'Sensor-100', 'Sensor-101', 'Sensor-102', 'Sensor-103', 'Sensor-104', 'Sensor-105', 'Sensor-106', 'Sensor-107', 'Sensor-108', 'Sensor-109', 'Sensor-110', 'Sensor-111', 'Sensor-112', 'Sensor-113', 'Sensor-114', 'Sensor-115', 'Sensor-116', 'Sensor-117', 'Sensor-118', 'Sensor-119', 'Sensor-120', 'Sensor-121', 'Sensor-122', 'Sensor-123', 'Sensor-124', 'Sensor-125', 'Sensor-126', 'Sensor-127', 'Sensor-128', 'Sensor-129', 'Sensor-130', 'Sensor-131', 'Sensor-132', 'Sensor-133', 'Sensor-134', 'Sensor-135', 'Sensor-136', 'Sensor-137', 'Sensor-138', 'Sensor-139', 'Sensor-140', 'Sensor-141', 'Sensor-143', 'Sensor-144', 'Sensor-145', 'Sensor-146', 'Sensor-147', 'Sensor-148', 'Sensor-149', 'Sensor-151', 'Sensor-152', 'Sensor-153', 'Sensor-154', 'Sensor-155', 'Sensor-156', 'Sensor-157', 'Sensor-160', 'Sensor-161', 'Sensor-162', 'Sensor-163', 'Sensor-164', 'Sensor-165', 'Sensor-166', 'Sensor-167', 'Sensor-168', 'Sensor-169', 'Sensor-170', 'Sensor-171', 'Sensor-172', 'Sensor-173', 'Sensor-174', 'Sensor-175', 'Sensor-176', 'Sensor-177', 'Sensor-178', 'Sensor-181', 'Sensor-182', 'Sensor-183', 'Sensor-184', 'Sensor-185', 'Sensor-186', 'Sensor-188', 'Sensor-189', 'Sensor-196', 'Sensor-197', 'Sensor-198', 'Sensor-199', 'Sensor-200', 'Sensor-201', 'Sensor-202', 'Sensor-203', 'Sensor-204', 'Sensor-205', 'Sensor-206', 'Sensor-208', 'Sensor-209', 'Sensor-211', 'Sensor-212', 'Sensor-213', 'Sensor-214', 'Sensor-215', 'Sensor-216', 'Sensor-217', 'Sensor-218', 'Sensor-219', 'Sensor-220', 'Sensor-221', 'Sensor-222', 'Sensor-223', 'Sensor-224', 'Sensor-225', 'Sensor-226', 'Sensor-228', 'Sensor-229', 'Sensor-239', 'Sensor-240', 'Sensor-245', 'Sensor-246', 'Sensor-247', 'Sensor-248', 'Sensor-249', 'Sensor-250', 'Sensor-251', 'Sensor-252', 'Sensor-253', 'Sensor-254', 'Sensor-255', 'Sensor-256', 'Sensor-268', 'Sensor-269', 'Sensor-270', 'Sensor-271', 'Sensor-272', 'Sensor-273', 'Sensor-274', 'Sensor-275', 'Sensor-276', 'Sensor-278', 'Sensor-279', 'Sensor-280', 'Sensor-281', 'Sensor-282', 'Sensor-283', 'Sensor-284', 'Sensor-286', 'Sensor-287', 'Sensor-288', 'Sensor-289', 'Sensor-290', 'Sensor-291', 'Sensor-292', 'Sensor-295', 'Sensor-296', 'Sensor-297', 'Sensor-298', 'Sensor-299', 'Sensor-300', 'Sensor-301', 'Sensor-302', 'Sensor-303', 'Sensor-304', 'Sensor-305', 'Sensor-306', 'Sensor-307', 'Sensor-308', 'Sensor-309', 'Sensor-310', 'Sensor-311', 'Sensor-312', 'Sensor-313', 'Sensor-317', 'Sensor-318', 'Sensor-319', 'Sensor-320', 'Sensor-321', 'Sensor-322', 'Sensor-324', 'Sensor-325', 'Sensor-332', 'Sensor-333', 'Sensor-334', 'Sensor-335', 'Sensor-336', 'Sensor-337', 'Sensor-338', 'Sensor-339', 'Sensor-340', 'Sensor-341', 'Sensor-342', 'Sensor-344', 'Sensor-345', 'Sensor-346', 'Sensor-347', 'Sensor-349', 'Sensor-350', 'Sensor-351', 'Sensor-352', 'Sensor-353', 'Sensor-354', 'Sensor-355', 'Sensor-356', 'Sensor-357', 'Sensor-358', 'Sensor-359', 'Sensor-360', 'Sensor-361', 'Sensor-362', 'Sensor-363', 'Sensor-364', 'Sensor-366', 'Sensor-367', 'Sensor-368', 'Sensor-369', 'Sensor-377', 'Sensor-378', 'Sensor-383', 'Sensor-384', 'Sensor-385', 'Sensor-386', 'Sensor-387', 'Sensor-388', 'Sensor-389', 'Sensor-390', 'Sensor-391', 'Sensor-392', 'Sensor-393', 'Sensor-394', 'Sensor-406', 'Sensor-407', 'Sensor-408', 'Sensor-409', 'Sensor-410', 'Sensor-411', 'Sensor-412', 'Sensor-413', 'Sensor-414', 'Sensor-416', 'Sensor-417', 'Sensor-418', 'Sensor-419', 'Sensor-420', 'Sensor-421', 'Sensor-422', 'Sensor-424', 'Sensor-425', 'Sensor-426', 'Sensor-427', 'Sensor-428', 'Sensor-429', 'Sensor-430', 'Sensor-431', 'Sensor-432', 'Sensor-433', 'Sensor-434', 'Sensor-435', 'Sensor-436', 'Sensor-437', 'Sensor-438', 'Sensor-439', 'Sensor-440', 'Sensor-441', 'Sensor-442', 'Sensor-443', 'Sensor-444', 'Sensor-445', 'Sensor-446', 'Sensor-447', 'Sensor-448', 'Sensor-449', 'Sensor-453', 'Sensor-454', 'Sensor-455', 'Sensor-456', 'Sensor-457', 'Sensor-458', 'Sensor-460', 'Sensor-461', 'Sensor-468', 'Sensor-469', 'Sensor-470', 'Sensor-471', 'Sensor-472', 'Sensor-473', 'Sensor-474', 'Sensor-475', 'Sensor-476', 'Sensor-477', 'Sensor-478', 'Sensor-480', 'Sensor-481', 'Sensor-483', 'Sensor-484', 'Sensor-485', 'Sensor-486', 'Sensor-487', 'Sensor-488', 'Sensor-489', 'Sensor-490', 'Sensor-491', 'Sensor-492', 'Sensor-493', 'Sensor-494', 'Sensor-495', 'Sensor-496', 'Sensor-497', 'Sensor-498', 'Sensor-500', 'Sensor-501', 'Sensor-511', 'Sensor-512', 'Sensor-517', 'Sensor-518', 'Sensor-519', 'Sensor-520', 'Sensor-521', 'Sensor-522', 'Sensor-523', 'Sensor-524', 'Sensor-525', 'Sensor-526', 'Sensor-527', 'Sensor-528', 'Sensor-540', 'Sensor-541', 'Sensor-542', 'Sensor-543', 'Sensor-544', 'Sensor-545', 'Sensor-546', 'Sensor-547', 'Sensor-548', 'Sensor-549', 'Sensor-550', 'Sensor-551', 'Sensor-552', 'Sensor-553', 'Sensor-554', 'Sensor-555', 'Sensor-556', 'Sensor-557', 'Sensor-558', 'Sensor-559', 'Sensor-560', 'Sensor-561', 'Sensor-562', 'Sensor-563', 'Sensor-564', 'Sensor-565', 'Sensor-566', 'Sensor-567', 'Sensor-568', 'Sensor-569', 'Sensor-570', 'Sensor-571', 'Sensor-572', 'Sensor-573', 'Sensor-574', 'Sensor-575', 'Sensor-576', 'Sensor-577', 'Sensor-578', 'Sensor-579', 'Sensor-580', 'Sensor-581', 'Sensor-582', 'Sensor-583', 'Sensor-584', 'Sensor-585', 'Sensor-586', 'Sensor-587']

In [40]:
len(num_cols)

460

* EXPERIMENT

In [ ]:
exp = num_cols
exp.remove('Sensor-1')

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [14]:
num_pipeline = Pipeline(

    steps = [('Imputer',SimpleImputer(strategy='median')),
             ('Scaler',StandardScaler())]
)

In [15]:
preprocessor = ColumnTransformer([('NumPipeline',num_pipeline,num_cols)])

In [16]:
x = wafer.iloc[:,:-1]
y = wafer.iloc[:,-1]

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=53,stratify=y)

In [18]:
y_train.value_counts()

Good/Bad
-1    75
 1     5
Name: count, dtype: int64

In [19]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.transform(x_test),columns=preprocessor.get_feature_names_out())

In [20]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=33,k_neighbors=2)

x_train, y_train = sm.fit_resample(x_train,y_train)

In [21]:
x_train.shape

(150, 464)

In [22]:
y_train.shape

(150,)

In [23]:
y_train.value_counts()

Good/Bad
-1    75
 1    75
Name: count, dtype: int64

## Model Training

In [24]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [25]:
models = {

'SVC' : SVC(kernel='rbf', C=1.0, gamma='scale'),
'DT' : DecisionTreeClassifier(criterion='entropy', max_depth=5, class_weight='balanced', random_state=33),
'RF' : RandomForestClassifier(n_estimators=100, 
    random_state=33, 
    class_weight='balanced',
    max_depth=10)
    
}

In [26]:
models.items()

dict_items([('SVC', SVC()), ('DT', DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=5, random_state=33)), ('RF', RandomForestClassifier(class_weight='balanced', max_depth=10, random_state=33))])

In [27]:
models.keys()

dict_keys(['SVC', 'DT', 'RF'])

In [28]:
models.values()

dict_values([SVC(), DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=5, random_state=33), RandomForestClassifier(class_weight='balanced', max_depth=10, random_state=33)])

In [29]:
for i in range(len(models)) :

    model = list(models.values())[i]
    model.fit(x_train,y_train)

    y_predicted = model.predict(x_test)

    reports = classification_report(y_test,y_predicted)

    print(list(models.keys())[i])
    print(reports)
    print("***********************************************")

c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

SVC
              precision    recall  f1-score   support

          -1       0.95      1.00      0.97        19
           1       0.00      0.00      0.00         1

    accuracy                           0.95        20
   macro avg       0.47      0.50      0.49        20
weighted avg       0.90      0.95      0.93        20

***********************************************
DT
              precision    recall  f1-score   support

          -1       0.95      1.00      0.97        19
           1       0.00      0.00      0.00         1

    accuracy                           0.95        20
   macro avg       0.47      0.50      0.49        20
weighted avg       0.90      0.95      0.93        20

***********************************************
RF
              precision    recall  f1-score   support

          -1       0.95      1.00      0.97        19
           1       0.00      0.00      0.00         1

    accuracy                           0.95        20
   macro avg       0.47      0.50      0.49        20
weighted avg       0.90      0.95      0.93        20

***********************************************

c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Admin\Desktop\WaferFaultDetectionnn\wafers_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
report = {}

for name,model in models.items() :

    model.fit(x_train,y_train)

    y_predicted = model.predict(x_test)

    accuracy = accuracy_score(y_test,y_predicted)

    report[name] = accuracy

In [39]:
report

{'SVC': 0.95, 'DT': 0.95, 'RF': 0.95}

In [41]:
dff = pd.read_csv(r"C:\Users\Admin\Desktop\WaferFaultDetectionnn\notebooks\data\wafer_23012020_041211 (1).csv")
dff.shape

(100, 592)

In [44]:
wafer.shape

(100, 465)